apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaoscarnival-demo
  namespace: app
  labels: 
    app: chaoscarnival-demo
spec:
  selector:
    matchLabels:
      app: chaoscarnival-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: chaoscarnival-demo
    spec:
      imagePullSecrets:
      - name: {{REGISTRY_PULL_SECRET}}
      containers:
      - name: chaoscarnival-demo
        image: {{DOCKER_IMAGE}}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: chaoscarnival-demo
  namespace: app
  labels:
    app: chaoscarnival-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: chaoscarnival-demo
